export const prompts = [
  "A futuristic cityscape at sunset, featuring towering skyscrapers with neon lights, flying cars weaving between buildings, and holographic billboards illuminating the sky.",
  "A serene forest with a cascading waterfall, surrounded by ancient towering trees, vibrant wildflowers, and a crystal-clear pond reflecting the lush greenery.",
  "An astronaut riding a majestic horse across the red sands of Mars, with the planet's rocky terrain stretching into the horizon and Earth visible as a distant blue dot in the sky.",
  "A dragon gracefully flying over a medieval castle perched on a rocky cliff, with banners fluttering in the wind, and a moat shimmering under the moonlight.",
  "A surreal landscape with floating islands connected by ornate bridges, vibrant flora blooming in impossible colors, and waterfalls cascading from one island to another into a misty abyss.",
  "A bustling cyberpunk street market at night, illuminated by colorful neon signs, with diverse vendors selling exotic goods, and pedestrians in futuristic attire navigating through the crowd.",
  "A magical library with endless bookshelves spiraling into the sky, enchanted books floating mid-air, and a grand chandelier made of crystals casting a radiant glow over the space.",
  "A steampunk-inspired airship sailing through fluffy white clouds, adorned with intricate gears and brass fittings, with passengers gazing out of large panoramic windows.",
  "A mystical underwater kingdom illuminated by bioluminescent corals, graceful mermaids swimming alongside ancient ruins, and schools of exotic fish darting through the vibrant marine flora.",
  "A vibrant coral reef teeming with life, showcasing a kaleidoscope of colorful fish, intricate coral formations, and sun rays piercing through the clear turquoise water.",
  "A minimalist black and white portrait of a lone figure standing at the edge of a vast desert, with swirling sand dunes and a dramatic cloudy sky creating a stark contrast.",
  "A vibrant abstract painting with bold colors and dynamic brushstrokes, depicting an explosion of shapes and patterns that evoke a sense of movement and emotion.",
  "A cozy cabin nestled in the snowy mountains during twilight, with smoke gently rising from the chimney, warm golden lights glowing through the windows, and snowflakes softly falling around.",
  "A bustling spaceport with various alien species boarding and disembarking from sleek spacecraft, towering structures adorned with intergalactic signage, and a lively atmosphere filled with activity.",
  "A tranquil Japanese garden in spring, featuring blooming cherry blossoms, a gently flowing koi pond, traditional stone lanterns, and a wooden bridge arching over a serene stream.",
  "A majestic phoenix rising from its ashes amidst a fiery backdrop, with vibrant feathers spread wide, illuminating the dark surroundings with its radiant glow.",
  "An enchanted forest at twilight, where luminescent plants and mythical creatures roam, casting ethereal lights and shadows under the canopy of ancient trees.",
  "A grand Victorian-era ballroom filled with elegantly dressed guests dancing under a magnificent chandelier, with intricate architectural details and opulent decorations.",
  "A whimsical fairy tale village perched on the branches of colossal trees, connected by rope bridges, with charming cottages, lantern-lit pathways, and magical creatures inhabiting the surroundings.",
  "A high-tech laboratory with sleek equipment, holographic displays, and scientists in futuristic attire conducting groundbreaking experiments, all set against a backdrop of advanced technology.",
  "A celestial scene depicting planets aligned in a vast galaxy, with shimmering stars, swirling nebulae, and cosmic phenomena creating a breathtaking and awe-inspiring panorama.",
  "A rustic farmhouse surrounded by golden fields of wheat under a clear blue sky, with a weathered barn, grazing livestock, and a peaceful countryside ambiance.",
  "An ancient underwater temple guarded by sea serpents, adorned with intricate carvings and surrounded by mysterious aquatic flora, illuminated by shafts of light filtering through the water.",
  "A dynamic battle scene between armored knights and mythical beasts in a stormy landscape, with lightning illuminating the chaotic skirmish and dramatic action frozen in time.",
  "A dreamy sunset over a tranquil lake, with reflections of colorful clouds dancing on the water's surface, framed by silhouetted trees and distant mountain peaks.",
  "A futuristic metropolis at night, with sprawling highways filled with autonomous vehicles, towering skyscrapers adorned with digital art, and vibrant street life illuminated by artificial lighting.",
  "A mystical sorceress casting a powerful spell in an ancient stone circle, with swirling magical energy, enchanted symbols glowing on the ground, and an aura of otherworldly power.",
  "A picturesque European village during autumn, with cobblestone streets lined with quaint houses, colorful fall foliage, and bustling local markets filled with seasonal produce.",
  "A vibrant street art mural coming to life, with characters and elements bursting out of the wall into the real world, blending reality with artistic imagination in a seamless transition.",
  "A serene beach at dawn, with gentle waves lapping against the shore, soft pastel colors painting the sky, and a solitary sailboat drifting peacefully on the horizon.",
];
